import { auth } from '@/auth';
import Dashboard from '@/shared/components/dashboard';
import type { Metadata } from 'next';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Home() {
   const session = await auth.api.getSession({ headers: await headers() });
    return(
        <Dashboard email={session?.user.email}/>
    )
}
